services:
  - type: web
    name: dulai-tree-api
    env: python
    plan: free          # upgrade later if traffic > 100 req/day
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    autoDeploy: true
    region: oregon
envVarGroups:
  - name: dulai-tree-env
    envVars:
      - key: OPENAI_API_KEY
        sync: false      # add value in dashboard
